# General runtime parameters
is_sim: 1
gtddp_optimize_node/is_gen: 1
target_timestep: 0.5
gtddp_optimize_node/gen_legs: 8

# DDP Type
ddp_select: "gtddp_cart_pole"

# DDP Hyperparameters
num_time_steps: 251
num_iterations: 70
num_long_legs: 8
short_iterations: 30
dt: 0.001
learning_rate: 0.3

# Cart-Pole System Parameters
num_states: 4
num_controls_u: 1
num_controls_v: 1
mass: 0.5
length: 2
cart_mass: 1
max_force: 50

# Initial conditions for u_traj
u_hover: [0]
v_hover: [0]

# Cost Function Parameters
Ru: [1]
Rv: [100]
Q: [1, 1, 1000000, 100000]
Qx_multiplier: 0.001

# Constrain the pursuit controls?
constrained: true
