##########################
# Simulator Mode
########################


# General runtime parameters
is_sim: 1
gtddp_optimize_node/is_gen: 0
target_timestep: 0.5
gtddp_optimize_node/gen_legs: 8

# DDP Type
ddp_select: "ccddp_cart_pole"

# DDP Hyperparameters
num_time_steps: 251
num_iterations: 70
num_long_legs: 2
short_iterations: 30
dt: 0.001
learning_rate: 0.3

# Cart-Pole System Parameters
num_states: 4
num_controls_u: 1
num_controls_v: 1
mass: 0.5
length: 2
cart_mass: 1
max_force: 50

# Convergence Hyperparameters
dist_converge_u: 1
dist_converge_v: 1

# Constraints for du
u_upper: [40]
u_lower: [-40]

# Constraints for dv
v_upper: [5]
v_lower: [-5]

# Initial conditions for u_traj
u_hover: [0]
v_hover: [0]

# Cost Function Parameters
Ru: [8]
Rv: [20]
Q: [1, 1, 1000000, 100000]
Qx_multiplier: 0.01

# Constrain the pursuit controls?
constrained: true
